services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/DevEvents:/app
    env_file:
      - .env
    command:
      - python
      - manage.py
      - populate_events
      - --clear
      - --count
      - '10'