services:
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: backend/src/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/src/backend
    environment:
      - PYTHONPATH=/src
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    env_file:
      - .env
    working_dir: /src
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/src
      - /src/node_modules
    depends_on:
      - backend

  migrations:
    build:
      context: .
      dockerfile: backend/src/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/src
    env_file:
      - .env
    command:
      - uv
      - run
      - alembic
      - revision
      - --autogenerate

volumes:
  postgres_data: