services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./DevEvents:/app
    env_file:
      - .env
    command:
      - python
      - manage.py
      - runserver
      - "0.0.0.0:8000"
  populate_data:

    build: 
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - .env
    command:
      - python
      - manage.py
      - populate_events
      - --clear
      - --count
      - '10'

    depends_on:
      - backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend