version: '3.8'

services:
  backend:
    build:
      context: ./backend/DevEvents    
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env

    working_dir: /app
    command:
      - python
      - manage.py
      - runserver
      - "0.0.0.0:8000"

  populate_data:
    build:
      context: ./backend/DevEvents
      dockerfile: Dockerfile
    volumes:
      - .:/app
    env_file:
      - .env
    working_dir: /app
    command:
      - python
      - manage.py
      - populate_events
      - --clear
      - --count
      - '10'
    depends_on:
      - backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend