repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.11.5
  hooks:
    - id: ruff
    - id: ruff-format

- repo: https://github.com/PyCQA/pep8-naming
  rev: 0.14.1
  hooks:
    - id: pep8-naming

- repo: https://github.com/PyCQA/docformatter
  rev: 1.7.5
  hooks:
    - id: docformatter

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.4.1
  hooks:
    -   id: mypy
